### PR TITLE
fix duplicate issue.

### PR DESCRIPTION
**Pull request by vshand11**
fixed the issue

### CODE REVIEW

**Review by n2iw — COMMENTED** [review]
If a CDE doesn't have version, we run the code twice, will it create duplicate? I suspect it still will?

**Comment by vshand11** [comment]
Will not.  after use get_CDE function to check if existing, it will return last version of CDE version is null.

**Comment by n2iw** [comment]
> Will not. after use get_CDE function to check if existing, it will return last version of CDE if version is null.

If you mean line 76 function get_cde_permissible_values(), at that time the code don't know the version (version is null in the model), right?

**Comment by vshand11** [comment]
The method in mongo_dao:
 """
    get CDE permissible values
    """    
    def get_cde_permissible_values(self, cde_code, cde_version):
        db = self.client[self.db_name]
        data_collection = db[CDE_COLLECTION]
        query = {CDE_CODE: cde_code}
        if cde_version:
            query[CDE_VERSION] = cde_version
        try:
            return data_collection.find_one(query, sort=[( 'CDE_VERSION', DESCENDING )])  #find latest version 
        except errors.PyMongoError as pe:
            self.log.exception(pe)
            self.log.exception(f"Failed to get permissible values for {cde_code}/{cde_version}: {get_exception_msg()}")
            return None
        except Exception as e:
            self.log.exception(e)
            self.log.exception(f"Failed to get permissible values for {cde_code}/{cde_version}: {get_exception_msg()}")
            return None

**Comment by vshand11** [comment]
the count method will not work correctly for version is null.  This one works.

**Review by n2iw — APPROVED** [review]
LGTM

**Pull request merged**
